import type { Repo, Run, HistoryRow } from './types'

export const REPOS: Repo[] = [
  {
    id: 'payments-svc',
    name: 'payments-svc',
    language: 'Go',
    health: 'ok',
    category: 'svc',
    liveAgents: 1,
    activity: [3, 4, 5, 4, 6, 5, 7, 4, 8],
    signals: { cves: 3, staleDeps: 18, flakyTests: 3, coverage: 72 },
    suggestedRuns: [
      { id: 'sr1', label: 'upgrade go-redis 8→9', detail: 'warn · 1 file', severity: 'warn' },
      { id: 'sr2', label: 'quarantine 3 flaky tests', detail: '/billing', severity: 'ok' },
      { id: 'sr3', label: 'fix CVE-2026-1142', detail: 'high · x/net', severity: 'err' },
    ],
    recentRuns: [
      { id: '9f3a', task: 'fix race · charge_handler', status: 'done', prId: '482' },
      { id: '9f39', task: 'upgrade go-redis 8→9', status: 'done', prId: '479' },
      { id: '9f37', task: 'docs for /v2 endpoints', status: 'running' },
    ],
  },
  {
    id: 'checkout-web',
    name: 'checkout-web',
    language: 'TS',
    health: 'ok',
    category: 'UI',
    liveAgents: 1,
    activity: [2, 3, 4, 3, 5, 4, 6],
    signals: { cves: 0, staleDeps: 5, flakyTests: 1, coverage: 88 },
    suggestedRuns: [
      { id: 'sr4', label: 'upgrade React 18→19', detail: 'minor · safe', severity: 'ok' },
      { id: 'sr5', label: 'fix a11y violations', detail: '4 issues', severity: 'warn' },
    ],
    recentRuns: [
      { id: '9f37', task: 'docs for /v2 endpoints', status: 'running' },
    ],
  },
  {
    id: 'ml-features',
    name: 'ml-features',
    language: 'Py',
    health: 'warn',
    category: 'ml',
    liveAgents: 1,
    activity: [1, 2, 3, 2, 4, 3, 2],
    signals: { cves: 1, staleDeps: 7, flakyTests: 5, coverage: 61 },
    suggestedRuns: [
      { id: 'sr6', label: 'pin numpy<2 breaking change', detail: 'err · tests fail', severity: 'err' },
    ],
    recentRuns: [],
  },
  {
    id: 'auth-edge',
    name: 'auth-edge',
    language: 'Rust',
    health: 'ok',
    category: 'svc',
    liveAgents: 0,
    activity: [2, 3, 3, 4, 3, 5, 4],
    signals: { cves: 0, staleDeps: 2, flakyTests: 0, coverage: 94 },
    suggestedRuns: [
      { id: 'sr7', label: 'refactor session store', detail: 'perf improvement', severity: 'ok' },
    ],
    recentRuns: [
      { id: '9f36', task: 'refactor session store', status: 'failed' },
    ],
  },
  {
    id: 'data-pipe',
    name: 'data-pipe',
    language: 'Py',
    health: 'err',
    category: 'etl',
    liveAgents: 0,
    activity: [5, 4, 3, 2, 3, 4, 2],
    signals: { cves: 4, staleDeps: 21, flakyTests: 8, coverage: 44 },
    suggestedRuns: [
      { id: 'sr8', label: 'fix CVE-2026-0887', detail: 'critical · sqlalchemy', severity: 'err' },
      { id: 'sr9', label: 'upgrade stale deps', detail: '21 outdated', severity: 'warn' },
    ],
    recentRuns: [
      { id: '9f35', task: 'CVE-2026-1142 patch', status: 'waiting' },
    ],
  },
  {
    id: 'mobile-ios',
    name: 'mobile-ios',
    language: 'Swift',
    health: 'ok',
    category: 'app',
    liveAgents: 0,
    activity: [2, 2, 3, 3, 4, 3, 4],
    signals: { cves: 0, staleDeps: 3, flakyTests: 2, coverage: 79 },
    suggestedRuns: [
      { id: 'sr10', label: 'update SwiftUI views for iOS 18', detail: 'compatibility', severity: 'warn' },
    ],
    recentRuns: [],
  },
  {
    id: 'notif-relay',
    name: 'notif-relay',
    language: 'Go',
    health: 'ok',
    category: 'svc',
    liveAgents: 0,
    activity: [2, 3, 2, 4, 3, 4, 3],
    signals: { cves: 0, staleDeps: 4, flakyTests: 0, coverage: 85 },
    suggestedRuns: [
      { id: 'sr11', label: 'generate openapi spec', detail: 'docs drift', severity: 'ok' },
    ],
    recentRuns: [
      { id: '9f34', task: 'generate openapi', status: 'done' },
    ],
  },
  {
    id: 'search-idx',
    name: 'search-idx',
    language: 'Java',
    health: 'ok',
    category: 'svc',
    liveAgents: 0,
    activity: [3, 3, 4, 3, 4, 5, 4],
    signals: { cves: 1, staleDeps: 9, flakyTests: 1, coverage: 77 },
    suggestedRuns: [
      { id: 'sr12', label: 'run integration suite', detail: '3 new tests added', severity: 'ok' },
    ],
    recentRuns: [
      { id: '9f33', task: 'run integration suite', status: 'done' },
    ],
  },
  {
    id: 'billing-svc',
    name: 'billing-svc',
    language: 'Go',
    health: 'ok',
    category: 'svc',
    liveAgents: 0,
    activity: [2, 3, 4, 5, 4, 5, 6],
    signals: { cves: 0, staleDeps: 6, flakyTests: 3, coverage: 81 },
    suggestedRuns: [
      { id: 'sr13', label: 'quarantine flaky tests', detail: '/billing · 3 tests', severity: 'warn' },
    ],
    recentRuns: [
      { id: '9f38', task: 'quarantine flaky tests', status: 'done' },
    ],
  },
  {
    id: 'api-gateway',
    name: 'api-gateway',
    language: 'Go',
    health: 'warn',
    category: 'svc',
    liveAgents: 0,
    activity: [4, 3, 5, 4, 3, 4, 5],
    signals: { cves: 2, staleDeps: 11, flakyTests: 0, coverage: 68 },
    suggestedRuns: [
      { id: 'sr14', label: 'patch rate-limiter CVE', detail: 'high · gorilla', severity: 'err' },
    ],
    recentRuns: [],
  },
  {
    id: 'infra-terraform',
    name: 'infra-terraform',
    language: 'Go',
    health: 'ok',
    category: 'svc',
    liveAgents: 0,
    activity: [1, 1, 2, 2, 1, 3, 2],
    signals: { cves: 0, staleDeps: 1, flakyTests: 0, coverage: 0 },
    suggestedRuns: [
      { id: 'sr15', label: 'update provider versions', detail: 'aws 5.x available', severity: 'ok' },
    ],
    recentRuns: [],
  },
  {
    id: 'docs-site',
    name: 'docs-site',
    language: 'TS',
    health: 'ok',
    category: 'UI',
    liveAgents: 0,
    activity: [1, 2, 1, 2, 3, 2, 1],
    signals: { cves: 0, staleDeps: 2, flakyTests: 0, coverage: 0 },
    suggestedRuns: [
      { id: 'sr16', label: 'sync API docs from OpenAPI', detail: 'docs drift', severity: 'warn' },
    ],
    recentRuns: [],
  },
]

export const SEED_RUNS: Run[] = [
  {
    id: '9f3a',
    repoId: 'payments-svc',
    task: 'fix race in charge_handler',
    status: 'done',
    startedAt: Date.now() - 4 * 60 * 1000,
    elapsedMs: 4 * 60 * 1000,
    prId: '482',
    tokens: { used: 4210, budget: 14000, cost: 0.021 },
    toolsUsed: ['read', 'grep', 'edit', 'test'],
    steps: [
      { id: 's1', label: 'plan · 3 steps drafted', status: 'done', duration: '08s', kind: null },
      {
        id: 's2',
        label: 'read charge_handler.go (314 ln)',
        status: 'done',
        duration: '12s',
        kind: 'files',
        files: [
          { path: 'charge_handler.go', meta: '314 ln', kind: 'read' },
          { path: 'stripe_client.go', meta: '88 ln', kind: 'read' },
        ],
      },
      {
        id: 's3',
        label: 'go test ./charge/...',
        status: 'done',
        duration: '06s',
        kind: 'term',
        terminal: [
          '$ go test ./charge/...',
          'ok   payments/charge       0.412s',
          'FAIL payments/charge/race  1.204s',
          '--- FAIL: TestDoubleDeliver (1.18s)',
          '    handler_test.go:142: expected 1 charge, got 2',
        ],
      },
      {
        id: 's4',
        label: 'edit charge_handler.go — add mutex around order_id',
        status: 'done',
        duration: '42s',
        kind: 'files',
        files: [
          { path: 'charge_handler.go', meta: '+8 / −2', kind: 'edit' },
          { path: 'webhook_test.go', meta: '+38', kind: 'new' },
        ],
      },
      { id: 's5', label: 'write regression test for double-deliver', status: 'done', duration: '18s', kind: null },
      { id: 's6', label: 'run tests + open PR', status: 'done', duration: '22s', kind: null },
    ],
  },
  {
    id: '9f37',
    repoId: 'checkout-web',
    task: 'docs for /v2 endpoints',
    status: 'running',
    startedAt: Date.now() - 90 * 1000,
    elapsedMs: 90 * 1000,
    tokens: { used: 1840, budget: 10000, cost: 0.009 },
    toolsUsed: ['read', 'edit'],
    steps: [
      { id: 's1', label: 'plan · 2 steps drafted', status: 'done', duration: '05s', kind: null },
      {
        id: 's2',
        label: 'read /v2 route handlers',
        status: 'done',
        duration: '09s',
        kind: 'files',
        files: [
          { path: 'src/routes/v2/checkout.ts', meta: '128 ln', kind: 'read' },
          { path: 'src/routes/v2/cart.ts', meta: '94 ln', kind: 'read' },
        ],
      },
      {
        id: 's3',
        label: 'write JSDoc for checkout endpoints',
        status: 'running',
        duration: '—',
        kind: 'files',
        files: [
          { path: 'src/routes/v2/checkout.ts', meta: '+32', kind: 'edit' },
        ],
      },
      { id: 's4', label: 'write JSDoc for cart endpoints', status: 'next', duration: '—', kind: null },
    ],
  },
]

export const HISTORY_ROWS: HistoryRow[] = [
  { id: '9f3a', task: 'fix race · charge_handler', repoId: 'payments-svc', status: 'done', duration: '4m', cost: '$0.06', prId: '482' },
  { id: '9f39', task: 'upgrade go-redis 8→9', repoId: 'payments-svc', status: 'done', duration: '11m', cost: '$0.18', prId: '479' },
  { id: '9f38', task: 'quarantine flaky tests', repoId: 'billing-svc', status: 'done', duration: '3m', cost: '$0.04', prId: '477' },
  { id: '9f37', task: 'docs for /v2 endpoints', repoId: 'checkout-web', status: 'running', duration: '—', cost: '$0.02' },
  { id: '9f36', task: 'refactor session store', repoId: 'auth-edge', status: 'failed', duration: '7m', cost: '$0.09' },
  { id: '9f35', task: 'CVE-2026-1142 patch', repoId: 'data-pipe', status: 'waiting', duration: '—', cost: '—' },
  { id: '9f34', task: 'generate openapi', repoId: 'notif-relay', status: 'done', duration: '2m', cost: '$0.02' },
  { id: '9f33', task: 'run integration suite', repoId: 'search-idx', status: 'done', duration: '9m', cost: '$0.12' },
]

export const RUN_TEMPLATES: Record<string, Omit<Run, 'id' | 'status' | 'startedAt' | 'elapsedMs'>> = {
  'fix-race': {
    repoId: 'payments-svc',
    task: 'fix race in charge_handler',
    tokens: { used: 0, budget: 14000, cost: 0 },
    toolsUsed: [],
    steps: [
      { id: 's1', label: 'plan · 3 steps drafted', status: 'next', kind: null },
      {
        id: 's2',
        label: 'read charge_handler.go (314 ln)',
        status: 'next',
        kind: 'files',
        files: [
          { path: 'charge_handler.go', meta: '314 ln', kind: 'read' },
          { path: 'stripe_client.go', meta: '88 ln', kind: 'read' },
        ],
      },
      {
        id: 's3',
        label: 'go test ./charge/...',
        status: 'next',
        kind: 'term',
        terminal: [
          '$ go test ./charge/...',
          'ok   payments/charge       0.412s',
          'FAIL payments/charge/race  1.204s',
          '--- FAIL: TestDoubleDeliver (1.18s)',
          '    handler_test.go:142: expected 1 charge, got 2',
        ],
      },
      {
        id: 's4',
        label: 'edit charge_handler.go — add mutex around order_id',
        status: 'next',
        kind: 'files',
        files: [
          { path: 'charge_handler.go', meta: '+8 / −2', kind: 'edit' },
          { path: 'webhook_test.go', meta: '+38', kind: 'new' },
        ],
      },
      { id: 's5', label: 'write regression test for double-deliver', status: 'next', kind: null },
      { id: 's6', label: 'run tests + open PR', status: 'next', kind: null },
    ],
  },
}
